/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Quick Start',
      items: ['quickstarts/ratify-on-aws', 'quickstarts/ratify-on-azure'],
    },
    {
      type: 'category',
      label: 'References',
      items: ['reference/executor', 'reference/error'],
    },
  ],

};

module.exports = sidebars;
